// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeliculasApiNETCore;

namespace PeliculasApiNETCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200821151845_dataprueba")]
    partial class dataprueba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.Actor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("id");

                    b.ToTable("Actores");

                    b.HasData(
                        new
                        {
                            id = 15,
                            fechaNacimiento = new DateTime(1962, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombre = "Jim Carrey"
                        },
                        new
                        {
                            id = 16,
                            fechaNacimiento = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombre = "Robert Downey Jr."
                        },
                        new
                        {
                            id = 17,
                            fechaNacimiento = new DateTime(1981, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombre = "Chris Evans"
                        });
                });

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            id = 14,
                            nombre = "Aventura"
                        },
                        new
                        {
                            id = 15,
                            nombre = "Animación"
                        },
                        new
                        {
                            id = 16,
                            nombre = "Suspenso"
                        },
                        new
                        {
                            id = 17,
                            nombre = "Romance"
                        });
                });

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.Pelicula", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("enCines")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaEstreno")
                        .HasColumnType("datetime2");

                    b.Property<string>("poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            id = 12,
                            enCines = true,
                            fechaEstreno = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            titulo = "Avengers: Endgame"
                        },
                        new
                        {
                            id = 13,
                            enCines = false,
                            fechaEstreno = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            titulo = "Avengers: Infinity Wars"
                        },
                        new
                        {
                            id = 14,
                            enCines = false,
                            fechaEstreno = new DateTime(2020, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            titulo = "Sonic the Hedgehog"
                        },
                        new
                        {
                            id = 15,
                            enCines = false,
                            fechaEstreno = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            titulo = "Emma"
                        },
                        new
                        {
                            id = 16,
                            enCines = false,
                            fechaEstreno = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            titulo = "Wonder Woman 1984"
                        });
                });

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.PeliculasActores", b =>
                {
                    b.Property<int>("actorId")
                        .HasColumnType("int");

                    b.Property<int>("peliculaId")
                        .HasColumnType("int");

                    b.Property<string>("nombrePersonaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orden")
                        .HasColumnType("int");

                    b.HasKey("actorId", "peliculaId");

                    b.HasIndex("peliculaId");

                    b.ToTable("PeliculasActores");

                    b.HasData(
                        new
                        {
                            actorId = 16,
                            peliculaId = 12,
                            nombrePersonaje = "Tony Stark",
                            orden = 1
                        },
                        new
                        {
                            actorId = 17,
                            peliculaId = 12,
                            nombrePersonaje = "Steve Rogers",
                            orden = 2
                        },
                        new
                        {
                            actorId = 16,
                            peliculaId = 13,
                            nombrePersonaje = "Tony Stark",
                            orden = 1
                        },
                        new
                        {
                            actorId = 17,
                            peliculaId = 13,
                            nombrePersonaje = "Steve Rogers",
                            orden = 2
                        },
                        new
                        {
                            actorId = 15,
                            peliculaId = 14,
                            nombrePersonaje = "Dr. Ivo Robotnik",
                            orden = 1
                        });
                });

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.PeliculasGeneros", b =>
                {
                    b.Property<int>("generoId")
                        .HasColumnType("int");

                    b.Property<int>("peliculaId")
                        .HasColumnType("int");

                    b.HasKey("generoId", "peliculaId");

                    b.HasIndex("peliculaId");

                    b.ToTable("PeliculasGeneros");

                    b.HasData(
                        new
                        {
                            generoId = 16,
                            peliculaId = 12
                        },
                        new
                        {
                            generoId = 14,
                            peliculaId = 12
                        },
                        new
                        {
                            generoId = 16,
                            peliculaId = 13
                        },
                        new
                        {
                            generoId = 14,
                            peliculaId = 13
                        },
                        new
                        {
                            generoId = 14,
                            peliculaId = 14
                        },
                        new
                        {
                            generoId = 16,
                            peliculaId = 15
                        },
                        new
                        {
                            generoId = 17,
                            peliculaId = 15
                        },
                        new
                        {
                            generoId = 16,
                            peliculaId = 16
                        },
                        new
                        {
                            generoId = 14,
                            peliculaId = 16
                        });
                });

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.PeliculasActores", b =>
                {
                    b.HasOne("PeliculasApiNETCore.Entidades.Actor", "actor")
                        .WithMany("peliculasActores")
                        .HasForeignKey("actorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeliculasApiNETCore.Entidades.Pelicula", "pelicula")
                        .WithMany("peliculasActores")
                        .HasForeignKey("peliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeliculasApiNETCore.Entidades.PeliculasGeneros", b =>
                {
                    b.HasOne("PeliculasApiNETCore.Entidades.Genero", "genero")
                        .WithMany("peliculasGeneros")
                        .HasForeignKey("generoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeliculasApiNETCore.Entidades.Pelicula", "pelicula")
                        .WithMany("peliculasGeneros")
                        .HasForeignKey("peliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
